
import React,{useState}from'react'
import{createRoot}from'react-dom/client'
import jsPDF from'jspdf'
import'./style.css'

const ICON='/ip-logo.png'
const SCOPES='https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/calendar.events'
const DISCOVERY=['https://sheets.googleapis.com/$discovery/rest?version=v4','https://www.googleapis.com/discovery/v1/apis/drive/v3/rest','https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest']
const LS_CFG='edf_google_cfg', LS_ED='edf_edificios', LS_IN='edf_inspecoes'
const SHEETS=['Folha_Classificacao_Edificios_Linha_Oeste_RJP','Lista de edifícios','Estações e Apeadeiros']
function load(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function today(){return new Date().toISOString().slice(0,10)}
function rowsToObjects(values){if(!values||values.length<2)return[];const h=values[0].map(x=>String(x).trim());return values.slice(1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
function val(o,ks){for(const k of ks){if(o[k])return String(o[k]).trim()}return''}
function badge(e){return ['Crítico','Mau','Alta','Urgente'].includes(e)?'danger':['Razoável','Média'].includes(e)?'warn':'ok'}

function App(){
 const[tab,setTab]=useState('dashboard')
 const[cfg,setCfg]=useState(load(LS_CFG,{apiKey:'',clientId:'',spreadsheetId:'',driveFolderId:'',calendarId:'primary'}))
 const[token,setToken]=useState(null),[status,setStatus]=useState('Desligado')
 const[edificios,setEdificios]=useState(load(LS_ED,[])),[inspecoes,setInspecoes]=useState(load(LS_IN,[]))
 const[sel,setSel]=useState(''),[insp,setInsp]=useState({data:today(),categoria:'Cobertura',estado:'Razoável',gravidade:'Média',prazo:'',descricao:'',acao:'',custo:'',fotos:[]})
 const ed=edificios.find(e=>e.id===sel), nav=[['dashboard','Dashboard'],['google','Google'],['edificios','Edifícios'],['inspecoes','Inspeções'],['drive','Drive/PDF'],['calendar','Calendar']]
 async function initGoogle(){if(!cfg.apiKey||!cfg.clientId)return alert('Preenche API Key e Client ID');setStatus('A ligar...');await new Promise(res=>{const w=()=>window.gapi&&window.google?res():setTimeout(w,200);w()});await new Promise(res=>window.gapi.load('client',res));await window.gapi.client.init({apiKey:cfg.apiKey,discoveryDocs:DISCOVERY});window.google.accounts.oauth2.initTokenClient({client_id:cfg.clientId,scope:SCOPES,callback:r=>{setToken(r.access_token);window.gapi.client.setToken(r);setStatus('Ligado ao Google')}}).requestAccessToken()}
 async function lerSheets(){if(!token||!cfg.spreadsheetId)return alert('Liga ao Google e indica Spreadsheet ID');setStatus('A ler folhas...');const ranges=SHEETS.map(s=>`${s}!A:Z`);const res=await window.gapi.client.sheets.spreadsheets.values.batchGet({spreadsheetId:cfg.spreadsheetId,ranges});const cls=rowsToObjects(res.result.valueRanges[0].values||[]), lista=rowsToObjects(res.result.valueRanges[1].values||[]);let eds=(cls.length?cls:lista).map((r,i)=>({id:val(r,['ID','Id'])||`LO-${i+1}`,estacao:val(r,['Estação/Local','Estação','Localização']),pk:val(r,['PK','Pk']),tipo:val(r,['Tipo de edifício','Tipo','Utilização Principal']),nome:val(r,['Tipo de edifício','Utilização Principal'])||'Edifício',estadoGlobal:val(r,['Estado global','Estado Global'])||'A avaliar',risco:val(r,['Risco']),urgencia:val(r,['Urgência']),intervencao:val(r,['Intervenção recomendada']),fotosDrive:val(r,['Fotos/Drive']),tecnico:val(r,['Técnico'])||'RJP'}));setEdificios(eds);save(LS_ED,eds);setStatus(`Carregados ${eds.length} edifícios`)}
 async function uploadDrive(file){const meta={name:file.name||`ficheiro_${Date.now()}`,mimeType:file.type||'application/octet-stream'};if(cfg.driveFolderId)meta.parents=[cfg.driveFolderId];const fd=new FormData();fd.append('metadata',new Blob([JSON.stringify(meta)],{type:'application/json'}));fd.append('file',file);const res=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink,name',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd});const out=await res.json();if(out.id)await window.gapi.client.drive.permissions.create({fileId:out.id,resource:{role:'reader',type:'anyone'}});return out}
 async function fotos(e){let arr=[];for(const f of [...e.target.files]){if(token){setStatus('A enviar foto...');const up=await uploadDrive(f);arr.push({name:f.name,link:up.webViewLink,id:up.id})}else{const local=await new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(f)});arr.push({name:f.name,local})}}setInsp({...insp,fotos:[...insp.fotos,...arr]});setStatus(token?'Fotos no Drive':'Fotos locais')}
 function guardarInsp(){if(!sel)return alert('Seleciona edifício');const item={...insp,id:crypto.randomUUID(),edificioId:sel,autor:'RJP'};const l=[item,...inspecoes];setInspecoes(l);save(LS_IN,l);setInsp({...insp,descricao:'',acao:'',custo:'',fotos:[]})}
 async function guardarInspecoes(){if(!token)return alert('Liga Google');const values=[['ID','EdificioID','Estação','Data','Categoria','Estado','Gravidade','Prazo','Descrição','Ação','Custo','Fotos','Autor'],...inspecoes.map(i=>{const e=edificios.find(x=>x.id===i.edificioId)||{};return[i.id,i.edificioId,e.estacao,i.data,i.categoria,i.estado,i.gravidade,i.prazo,i.descricao,i.acao,i.custo,(i.fotos||[]).map(f=>f.link||f.name).join(' | '),'RJP']})];await window.gapi.client.sheets.spreadsheets.values.update({spreadsheetId:cfg.spreadsheetId,range:'Inspecoes_App!A1',valueInputOption:'USER_ENTERED',resource:{values}});setStatus('Inspeções guardadas no Sheets')}
 async function pdf(){if(!ed)return alert('Seleciona edifício');const p=new jsPDF();p.setFillColor(23,181,164);p.rect(0,0,210,28,'F');p.setTextColor(255,255,255);p.setFontSize(17);p.text('EDF_Oeste',12,13);p.setFontSize(10);p.text('Gestão de Edifícios e Manutenção · Autor: RJP',12,20);p.setTextColor(0,0,0);p.setFontSize(13);p.text(`${ed.estacao} | ${ed.id} | PK ${ed.pk||'-'}`,12,40);p.setFontSize(10);p.text(`Estado: ${ed.estadoGlobal||'-'} | Tipo: ${ed.tipo||'-'}`,12,48);let y=60;inspecoes.filter(i=>i.edificioId===ed.id).forEach((i,n)=>{p.text(`${n+1}. ${i.data} - ${i.categoria} - ${i.estado}`,12,y);y+=7;p.text(p.splitTextToSize(i.descricao||'-',180),12,y);y+=12});const blob=p.output('blob');if(token){const up=await uploadDrive(new File([blob],`EDF_Oeste_${ed.id}_${today()}.pdf`,{type:'application/pdf'}));setStatus('PDF no Drive');alert(up.webViewLink)}else p.save(`EDF_Oeste_${ed.id}.pdf`)}
 async function evento(){if(!token||!ed||!insp.prazo)return alert('Liga Google, seleciona edifício e prazo');const s=new Date(insp.prazo+'T09:00:00'), e=new Date(insp.prazo+'T10:00:00');await window.gapi.client.calendar.events.insert({calendarId:cfg.calendarId||'primary',resource:{summary:`EDF_Oeste - ${ed.estacao}`,description:insp.acao||insp.descricao,start:{dateTime:s.toISOString()},end:{dateTime:e.toISOString()}}});setStatus('Evento criado')}
 return <div><header className="top"><div className="brand"><img className="brand-logo" src={ICON}/><div><h1>EDF_Oeste</h1><p>Gestão de Edifícios e Manutenção</p><div className="author">Autor: RJP</div></div></div></header><nav className="tabs">{nav.map(([id,n])=><button key={id} onClick={()=>setTab(id)} className={'tab '+(tab===id?'active':'')}>{n}</button>)}</nav><main className="container">
 {tab==='dashboard'&&<section className="grid"><div className="card"><h3>Edifícios</h3><div className="kpi">{edificios.length}</div></div><div className="card"><h3>Inspeções</h3><div className="kpi">{inspecoes.length}</div></div><div className="card"><h3>Google</h3><p>{status}</p><button className="btn" onClick={()=>setTab('google')}>Configurar</button></div></section>}
 {tab==='google'&&<section className="grid"><div className="card"><h2>Google APIs</h2><label>API Key</label><input value={cfg.apiKey} onChange={e=>setCfg({...cfg,apiKey:e.target.value})}/><label>Client ID</label><input value={cfg.clientId} onChange={e=>setCfg({...cfg,clientId:e.target.value})}/><label>Spreadsheet ID</label><input value={cfg.spreadsheetId} onChange={e=>setCfg({...cfg,spreadsheetId:e.target.value})}/><label>Drive Folder ID</label><input value={cfg.driveFolderId} onChange={e=>setCfg({...cfg,driveFolderId:e.target.value})}/><label>Calendar ID</label><input value={cfg.calendarId} onChange={e=>setCfg({...cfg,calendarId:e.target.value})}/><button className="btn" onClick={()=>{save(LS_CFG,cfg);alert('Guardado')}}>Guardar</button><button className="btn secondary" onClick={initGoogle}>Ligar Google</button><button className="btn secondary" onClick={lerSheets}>Ler 3 folhas</button></div><div className="card"><h3>Folhas</h3>{SHEETS.map(s=><p key={s}>{s}</p>)}</div></section>}
 {tab==='edificios'&&<section className="card"><h2>Edifícios</h2>{edificios.map(e=><div className="item" key={e.id}><div className="thumb">🏢</div><div><b>{e.estacao}</b><div className="small">{e.id} · PK {e.pk||'-'} · {e.tipo}</div><span className={'badge '+badge(e.estadoGlobal)}>{e.estadoGlobal}</span><br/><button className="btn secondary" onClick={()=>{setSel(e.id);setTab('inspecoes')}}>Inspecionar</button></div></div>)}</section>}
 {tab==='inspecoes'&&<section className="grid"><div className="card"><h2>Nova inspeção</h2><label>Edifício</label><select value={sel} onChange={e=>setSel(e.target.value)}><option value="">Selecionar</option>{edificios.map(e=><option value={e.id} key={e.id}>{e.estacao} - {e.id}</option>)}</select><div className="row"><div><label>Data</label><input type="date" value={insp.data} onChange={e=>setInsp({...insp,data:e.target.value})}/></div><div><label>Categoria</label><input value={insp.categoria} onChange={e=>setInsp({...insp,categoria:e.target.value})}/></div></div><div className="row3"><div><label>Estado</label><select value={insp.estado} onChange={e=>setInsp({...insp,estado:e.target.value})}>{['Bom','Razoável','Mau','Crítico'].map(x=><option key={x}>{x}</option>)}</select></div><div><label>Gravidade</label><select value={insp.gravidade} onChange={e=>setInsp({...insp,gravidade:e.target.value})}>{['Baixa','Média','Alta','Urgente'].map(x=><option key={x}>{x}</option>)}</select></div><div><label>Prazo</label><input type="date" value={insp.prazo} onChange={e=>setInsp({...insp,prazo:e.target.value})}/></div></div><label>Descrição</label><textarea value={insp.descricao} onChange={e=>setInsp({...insp,descricao:e.target.value})}/><label>Ação</label><textarea value={insp.acao} onChange={e=>setInsp({...insp,acao:e.target.value})}/><label>Custo</label><input value={insp.custo} onChange={e=>setInsp({...insp,custo:e.target.value})}/><label>Fotos</label><input type="file" multiple accept="image/*" capture="environment" onChange={fotos}/><div className="photo-grid">{insp.fotos.map((f,i)=><img key={i} src={f.local||f.link}/>)}</div><button className="btn" onClick={guardarInsp}>Guardar inspeção</button><button className="btn secondary" onClick={guardarInspecoes}>Guardar no Sheets</button></div><div className="card"><h2>Histórico</h2>{inspecoes.filter(i=>!sel||i.edificioId===sel).map(i=><div className="item" key={i.id}><div className="thumb">📋</div><div><b>{i.data} - {i.categoria}</b><br/><span className={'badge '+badge(i.estado)}>{i.estado}</span><p>{i.descricao}</p></div></div>)}</div></section>}
 {tab==='drive'&&<section className="card"><h2>Drive / PDF</h2><button className="btn" onClick={pdf}>Gerar PDF e guardar no Drive</button></section>}
 {tab==='calendar'&&<section className="card"><h2>Google Calendar</h2><p>Cria evento com o prazo da inspeção atual.</p><button className="btn" onClick={evento}>Criar evento</button></section>}
 </main><p className="footer-note">EDF_Oeste · Autor RJP · Google Sheets / Drive / Calendar</p></div>
}
createRoot(document.getElementById('root')).render(<App/>)
