
import React,{useState}from'react'
import{createRoot}from'react-dom/client'
import jsPDF from'jspdf'
import * as XLSX from'xlsx'
import'./style.css'

const estacoes=['Sabugo','Pedra Furada','Mafra','Malveira','Jerumelo','Sapataria','Pero Negro','Zibreira','Feliteira','Dois Portos','Runa','Torres Vedras','Ramalhal','Outeiro','Camarão','Bombarral','Paúl','São Mamede','Dagorda-Peniche','Óbidos','Caldas da Rainha','Campo-Serra','Bouro','Salir do Porto','São Martinho do Porto','Famalicão-Nazaré','Cela','Valado','Fanhais','Pataias','Martingança','Marinha Grande','Leiria','Regueira de Pontes','Monte Real','Monte Redondo','Guia','Carriço']
const categorias=['Cobertura','Fachadas','Caixilharias','Pinturas','Pavimentos','Instalações elétricas','Águas e esgotos','Drenagem','Acessibilidades','Segurança contra incêndio','Muros','Vedações','Outro']
const estados=['Bom','Razoável','Mau','Crítico']
const tipos=['Estação','Apeadeiro','Armazém','Casa de guarda','Edifício técnico','Posto de transformação','Outro']
const ICON='/ip-logo.png'
const LS_ED='edf_oeste_edificios', LS_IN='edf_oeste_inspecoes', LS_SYNC='edf_oeste_sync'
function load(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function today(){return new Date().toISOString().slice(0,10)}
function badgeEstado(e){return e==='Crítico'||e==='Mau'?'danger':e==='Razoável'?'warn':'ok'}
function val(row,names){for(const n of names){if(row[n]!==undefined&&row[n]!==null)return String(row[n]).trim()}return''}

function App(){
 const[tab,setTab]=useState('dashboard')
 const[edificios,setEdificios]=useState(load(LS_ED,[]))
 const[inspecoes,setInspecoes]=useState(load(LS_IN,[]))
 const[sync,setSync]=useState(load(LS_SYNC,{scriptUrl:'',sheetUrl:'',driveFolder:'',status:'Offline/local'}))
 const[sel,setSel]=useState('')
 const[importLog,setImportLog]=useState('')
 const[edf,setEdf]=useState({estacao:'Leiria',tipo:'Estação',nome:'',pk:'',gps:'',ano:'',pisos:'',areaBruta:'',areaCoberta:'',areaFachadas:'',obs:''})
 const[insp,setInsp]=useState({data:today(),categoria:'Cobertura',estado:'Razoável',gravidade:'Média',prazo:'',responsavel:'',descricao:'',acao:'',comprimento:'',largura:'',altura:'',area:'',custo:'',fotos:[]})
 const persist=(eds,ins)=>{setEdificios(eds);setInspecoes(ins);save(LS_ED,eds);save(LS_IN,ins)}
 const guardarEdificio=()=>{const item={...edf,id:crypto.randomUUID(),criado:today(),autor:'RJP'};const lista=[item,...edificios];setEdificios(lista);save(LS_ED,lista);setSel(item.id);setTab('inspecoes')}
 const guardarInspecao=()=>{if(!sel){alert('Seleciona primeiro um edifício.');return}const item={...insp,edificioId:sel,id:crypto.randomUUID(),criado:today(),autor:'RJP'};const lista=[item,...inspecoes];setInspecoes(lista);save(LS_IN,lista);setInsp({...insp,descricao:'',acao:'',comprimento:'',largura:'',altura:'',area:'',custo:'',fotos:[]})}
 const getGps=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>setEdf({...edf,gps:`${p.coords.latitude.toFixed(7)}, ${p.coords.longitude.toFixed(7)}`}),()=>alert('Não foi possível obter GPS.')):alert('GPS indisponível.')
 const addFotos=async(e)=>{const fs=[...e.target.files];const arr=await Promise.all(fs.map(f=>new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(f)})));setInsp({...insp,fotos:[...insp.fotos,...arr]})}
 const guardarSync=()=>{save(LS_SYNC,sync);alert('Configuração guardada.')}
 const enviarGoogle=async()=>{if(!sync.scriptUrl){alert('Falta URL do Apps Script.');return}try{await fetch(sync.scriptUrl,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({app:'EDF_Oeste',autor:'RJP',edificios,inspecoes})});const ns={...sync,status:'Enviado para Google em '+new Date().toLocaleString('pt-PT')};setSync(ns);save(LS_SYNC,ns);alert('Enviado.')}catch(e){alert('Erro: '+e.message)}}
 const receberGoogle=async()=>{if(!sync.scriptUrl){alert('Falta URL do Apps Script.');return}try{const r=await fetch(sync.scriptUrl+'?app=EDF_Oeste');const d=await r.json();persist(d.edificios||[],d.inspecoes||[]);const ns={...sync,status:'Recebido do Google em '+new Date().toLocaleString('pt-PT')};setSync(ns);save(LS_SYNC,ns)}catch(e){alert('Erro: '+e.message)}}
 const importarExcel=async(e)=>{const file=e.target.files[0];if(!file)return;const data=await file.arrayBuffer();const wb=XLSX.read(data);let novosE=[...edificios], novasI=[...inspecoes];const getSheet=names=>names.map(n=>wb.Sheets[n]).find(Boolean);let ce=0,ci=0;const shEd=getSheet(['Edificios','Edifícios','Cadastro']);const shIn=getSheet(['Inspecoes','Inspeções','Manutenção','Manutencao']);if(shEd){XLSX.utils.sheet_to_json(shEd,{defval:''}).forEach(r=>{const nome=val(r,['Nome','Edificio','Edifício','nome']);const estacao=val(r,['Estacao','Estação','estacao'])||'Sem estação';novosE.unshift({id:crypto.randomUUID(),criado:today(),autor:'RJP',estacao,tipo:val(r,['Tipo','tipo'])||'Estação',nome:nome||estacao,pk:val(r,['PK','Pk','pk']),gps:val(r,['GPS','Gps','gps']),ano:val(r,['Ano','ano']),pisos:val(r,['Pisos','pisos']),areaBruta:val(r,['AreaBruta','Área bruta','Area bruta']),areaCoberta:val(r,['AreaCoberta','Área cobertura','Area cobertura']),areaFachadas:val(r,['AreaFachadas','Área fachadas','Area fachadas']),obs:val(r,['Observacoes','Observações','Obs','obs'])});ce++})}if(shIn){XLSX.utils.sheet_to_json(shIn,{defval:''}).forEach(r=>{const estacao=val(r,['Estacao','Estação','estacao']);const nome=val(r,['Edificio','Edifício','Nome','nome']);let ed=novosE.find(x=>(nome&&(x.nome||'').toLowerCase()===nome.toLowerCase())||(estacao&&(x.estacao||'').toLowerCase()===estacao.toLowerCase()));if(!ed){ed={id:crypto.randomUUID(),criado:today(),autor:'RJP',estacao:estacao||'Sem estação',tipo:'Estação',nome:nome||estacao||'Edifício importado'};novosE.unshift(ed);ce++}novasI.unshift({id:crypto.randomUUID(),criado:today(),autor:'RJP',edificioId:ed.id,data:val(r,['Data','data'])||today(),categoria:val(r,['Categoria','Elemento'])||'Outro',estado:val(r,['Estado'])||'Razoável',gravidade:val(r,['Gravidade'])||'Média',prazo:val(r,['Prazo']),responsavel:val(r,['Responsavel','Responsável']),descricao:val(r,['Descricao','Descrição','Anomalia']),acao:val(r,['Acao','Ação','Medida']),comprimento:val(r,['Comprimento']),largura:val(r,['Largura']),altura:val(r,['Altura']),area:val(r,['Area','Área']),custo:val(r,['Custo','Estimativa']),fotos:[]});ci++})}persist(novosE,novasI);setImportLog(`Importação: ${ce} edifícios e ${ci} inspeções.`)}
 const exportarExcel=()=>{const edRows=edificios.map(e=>({Estação:e.estacao,Tipo:e.tipo,Nome:e.nome,PK:e.pk,GPS:e.gps,Ano:e.ano,Pisos:e.pisos,AreaBruta:e.areaBruta,AreaCoberta:e.areaCoberta,AreaFachadas:e.areaFachadas,Observações:e.obs,Autor:'RJP'}));const inRows=inspecoes.map(i=>{const e=edificios.find(x=>x.id===i.edificioId)||{};return{Estação:e.estacao,Edifício:e.nome,Data:i.data,Categoria:i.categoria,Estado:i.estado,Gravidade:i.gravidade,Prazo:i.prazo,Responsável:i.responsavel,Descrição:i.descricao,Ação:i.acao,Comprimento:i.comprimento,Largura:i.largura,Altura:i.altura,Área:i.area,Custo:i.custo,Autor:'RJP'}});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(edRows),'Edificios');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(inRows),'Inspecoes');XLSX.writeFile(wb,'EDF_Oeste_RJP.xlsx')}
 const gerarModelo=()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Estação:'Leiria',Tipo:'Estação',Nome:'Edifício de passageiros',PK:'',GPS:'',Ano:'',Pisos:'2',AreaBruta:'',AreaCoberta:'',AreaFachadas:'',Observações:''}]),'Edificios');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Estação:'Leiria',Edifício:'Edifício de passageiros',Data:today(),Categoria:'Cobertura',Estado:'Razoável',Gravidade:'Média',Prazo:'',Responsável:'',Descrição:'',Ação:'',Comprimento:'',Largura:'',Altura:'',Área:'',Custo:''}]),'Inspecoes');XLSX.writeFile(wb,'Modelo_EDF_Oeste_RJP.xlsx')}
 const apagarEdificio=id=>persist(edificios.filter(x=>x.id!==id),inspecoes.filter(x=>x.edificioId!==id))
 const apagarInspecao=id=>persist(edificios,inspecoes.filter(x=>x.id!==id))
 const edAtual=edificios.find(e=>e.id===sel); const inspLista=sel?inspecoes.filter(i=>i.edificioId===sel):inspecoes
 const criticas=inspecoes.filter(i=>i.estado==='Crítico'||i.estado==='Mau').length
 const custoTotal=inspecoes.reduce((s,i)=>s+(Number(String(i.custo).replace(',','.'))||0),0)
 const gerarPdf=id=>{const ed=edificios.find(e=>e.id===id)||edAtual;if(!ed){alert('Seleciona um edifício.');return}const lista=inspecoes.filter(i=>i.edificioId===ed.id);const pdf=new jsPDF();let y=13;pdf.setFillColor(23,181,164);pdf.rect(0,0,210,28,'F');pdf.setTextColor(255,255,255);pdf.setFont('helvetica','bold');pdf.setFontSize(17);pdf.text('EDF_Oeste',12,y);y+=7;pdf.setFontSize(10);pdf.text('Gestão de Edifícios e Manutenção · Autor: RJP',12,y);pdf.setTextColor(0,0,0);y=38;pdf.setFont('helvetica','bold');pdf.setFontSize(14);pdf.text(`Relatório técnico - ${ed.nome||ed.estacao}`,12,y);y+=8;pdf.setFontSize(10);pdf.setFont('helvetica','normal');pdf.text(`Estação: ${ed.estacao} | Tipo: ${ed.tipo} | PK: ${ed.pk||'-'}`,12,y);y+=7;pdf.text(`GPS: ${ed.gps||'-'} | Área bruta: ${ed.areaBruta||'-'} m² | Cobertura: ${ed.areaCoberta||'-'} m²`,12,y);y+=10;pdf.setFont('helvetica','bold');pdf.text('Inspeções / Não conformidades',12,y);y+=7;pdf.setFont('helvetica','normal');lista.forEach((i,idx)=>{if(y>268){pdf.addPage();y=16}pdf.setFont('helvetica','bold');pdf.text(`${idx+1}. ${i.data} - ${i.categoria} - ${i.estado}`,12,y);y+=6;pdf.setFont('helvetica','normal');const l1=pdf.splitTextToSize(`Descrição: ${i.descricao||'-'}`,180);pdf.text(l1,12,y);y+=l1.length*5;const l2=pdf.splitTextToSize(`Ação: ${i.acao||'-'} | Prazo: ${i.prazo||'-'} | Custo: ${i.custo||'0'} euros`,180);pdf.text(l2,12,y);y+=l2.length*5+3});pdf.setFontSize(8);pdf.text('Documento gerado automaticamente pela aplicação EDF_Oeste. Autor: RJP.',12,288);pdf.save(`EDF_Oeste_${ed.estacao}.pdf`)}

 return <div><header className="app-header"><div className="brand"><img className="logo" src={ICON}/><div><h1>EDF_Oeste</h1><p>Gestão de Edifícios e Manutenção</p><div className="author">Autor: RJP</div></div></div></header>
 <nav className="tabs">{[['dashboard','Resumo'],['sync','Sincronização'],['excel','Excel/Sheets'],['edificios','Edifícios'],['inspecoes','Inspeções'],['manutencao','Manutenção'],['relatorios','Relatórios']].map(([id,n])=><button key={id} onClick={()=>setTab(id)} className={'tab '+(tab===id?'active':'')}>{n}</button>)}</nav>
 <main className="container">
 {tab==='dashboard'&&<section className="grid"><div className="card"><h3>Edifícios</h3><div className="kpi">{edificios.length}</div></div><div className="card"><h3>Inspeções</h3><div className="kpi">{inspecoes.length}</div></div><div className="card"><h3>Prioridade alta</h3><div className="kpi">{criticas}</div></div><div className="card"><h3>Custo estimado</h3><div className="kpi">{custoTotal.toFixed(0)} €</div></div></section>}
 {tab==='sync'&&<section className="grid"><div className="card"><h2>Sincronização Google</h2><div className="syncbox"><b>Estado:</b> {sync.status}</div><label>URL do Google Apps Script</label><input value={sync.scriptUrl} onChange={e=>setSync({...sync,scriptUrl:e.target.value})}/><label>Link Google Sheet</label><input value={sync.sheetUrl} onChange={e=>setSync({...sync,sheetUrl:e.target.value})}/><label>Pasta Drive fotos/PDF</label><input value={sync.driveFolder} onChange={e=>setSync({...sync,driveFolder:e.target.value})}/><button className="btn" onClick={guardarSync}>Guardar</button><button className="btn secondary" onClick={enviarGoogle}>Enviar</button><button className="btn secondary" onClick={receberGoogle}>Receber</button></div></section>}
 {tab==='excel'&&<section className="grid"><div className="card"><h2>Excel / Google Sheets</h2><input type="file" accept=".xlsx,.xls" onChange={importarExcel}/>{importLog&&<p><span className="badge ok">{importLog}</span></p>}<button className="btn secondary" onClick={gerarModelo}>Modelo Excel</button><button className="btn" onClick={exportarExcel}>Exportar Excel</button></div><div className="card"><h3>Folhas</h3><p><b>Edificios</b> e <b>Inspecoes</b>.</p></div></section>}
 {tab==='edificios'&&<section className="grid"><div className="card"><h2>Novo edifício</h2><div className="row"><div><label>Estação</label><select value={edf.estacao} onChange={e=>setEdf({...edf,estacao:e.target.value})}>{estacoes.map(x=><option key={x}>{x}</option>)}</select></div><div><label>Tipo</label><select value={edf.tipo} onChange={e=>setEdf({...edf,tipo:e.target.value})}>{tipos.map(x=><option key={x}>{x}</option>)}</select></div></div><label>Nome</label><input value={edf.nome} onChange={e=>setEdf({...edf,nome:e.target.value})}/><div className="row3"><div><label>PK</label><input value={edf.pk} onChange={e=>setEdf({...edf,pk:e.target.value})}/></div><div><label>Ano</label><input value={edf.ano} onChange={e=>setEdf({...edf,ano:e.target.value})}/></div><div><label>Pisos</label><input value={edf.pisos} onChange={e=>setEdf({...edf,pisos:e.target.value})}/></div></div><label>GPS</label><input value={edf.gps} onChange={e=>setEdf({...edf,gps:e.target.value})}/><button className="btn secondary" onClick={getGps}>Obter GPS</button><div className="row3"><div><label>Área bruta</label><input value={edf.areaBruta} onChange={e=>setEdf({...edf,areaBruta:e.target.value})}/></div><div><label>Área cobertura</label><input value={edf.areaCoberta} onChange={e=>setEdf({...edf,areaCoberta:e.target.value})}/></div><div><label>Área fachadas</label><input value={edf.areaFachadas} onChange={e=>setEdf({...edf,areaFachadas:e.target.value})}/></div></div><label>Observações</label><textarea value={edf.obs} onChange={e=>setEdf({...edf,obs:e.target.value})}/><button className="btn full" onClick={guardarEdificio}>Guardar</button></div><div className="card"><h2>Lista</h2>{edificios.map(e=><div className="item" key={e.id}><div className="item-title">{e.estacao} — {e.nome||e.tipo}</div><div className="small">{e.tipo} | PK {e.pk||'-'} | Autor RJP</div><button className="btn secondary" onClick={()=>{setSel(e.id);setTab('inspecoes')}}>Selecionar</button><button className="btn secondary" onClick={()=>gerarPdf(e.id)}>PDF</button><button className="btn danger" onClick={()=>apagarEdificio(e.id)}>Apagar</button></div>)}</div></section>}
 {tab==='inspecoes'&&<section className="grid"><div className="card"><h2>Nova inspeção</h2><label>Edifício</label><select value={sel} onChange={e=>setSel(e.target.value)}><option value="">Selecionar...</option>{edificios.map(e=><option key={e.id} value={e.id}>{e.estacao} — {e.nome||e.tipo}</option>)}</select><div className="row"><div><label>Data</label><input type="date" value={insp.data} onChange={e=>setInsp({...insp,data:e.target.value})}/></div><div><label>Categoria</label><select value={insp.categoria} onChange={e=>setInsp({...insp,categoria:e.target.value})}>{categorias.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="row3"><div><label>Estado</label><select value={insp.estado} onChange={e=>setInsp({...insp,estado:e.target.value})}>{estados.map(x=><option key={x}>{x}</option>)}</select></div><div><label>Gravidade</label><select value={insp.gravidade} onChange={e=>setInsp({...insp,gravidade:e.target.value})}>{['Baixa','Média','Alta','Urgente'].map(x=><option key={x}>{x}</option>)}</select></div><div><label>Prazo</label><input type="date" value={insp.prazo} onChange={e=>setInsp({...insp,prazo:e.target.value})}/></div></div><label>Descrição</label><textarea value={insp.descricao} onChange={e=>setInsp({...insp,descricao:e.target.value})}/><label>Ação proposta</label><textarea value={insp.acao} onChange={e=>setInsp({...insp,acao:e.target.value})}/><div className="row3"><div><label>Comprimento</label><input value={insp.comprimento} onChange={e=>setInsp({...insp,comprimento:e.target.value})}/></div><div><label>Largura</label><input value={insp.largura} onChange={e=>setInsp({...insp,largura:e.target.value})}/></div><div><label>Altura</label><input value={insp.altura} onChange={e=>setInsp({...insp,altura:e.target.value})}/></div></div><div className="row"><div><label>Área m²</label><input value={insp.area} onChange={e=>setInsp({...insp,area:e.target.value})}/></div><div><label>Custo €</label><input value={insp.custo} onChange={e=>setInsp({...insp,custo:e.target.value})}/></div></div><label>Fotos</label><input type="file" multiple accept="image/*" capture="environment" onChange={addFotos}/><div className="photo-grid">{insp.fotos.map((f,i)=><img src={f} key={i}/>)}</div><button className="btn full" onClick={guardarInspecao}>Guardar inspeção</button></div><div className="card"><h2>{edAtual?`${edAtual.estacao} — ${edAtual.nome||edAtual.tipo}`:'Inspeções'}</h2>{inspLista.map(i=><div className="item" key={i.id}><div className="item-title">{i.data} — {i.categoria}</div><span className={'badge '+badgeEstado(i.estado)}>{i.estado}</span><span className="badge info">{i.gravidade}</span><p>{i.descricao||'Sem descrição'}</p><p className="small">Ação: {i.acao||'-'} | Prazo: {i.prazo||'-'} | Custo: {i.custo||0} €</p><div className="photo-grid">{(i.fotos||[]).map((f,k)=><img src={f} key={k}/>)}</div><button className="btn danger" onClick={()=>apagarInspecao(i.id)}>Apagar</button></div>)}</div></section>}
 {tab==='manutencao'&&<section className="card"><h2>Plano de manutenção</h2><div className="tablewrap"><table><thead><tr><th>Data/Prazo</th><th>Estação</th><th>Edifício</th><th>Elemento</th><th>Estado</th><th>Ação</th><th>Custo</th></tr></thead><tbody>{inspecoes.map(i=>{const e=edificios.find(x=>x.id===i.edificioId)||{};return <tr key={i.id}><td>{i.prazo||i.data}</td><td>{e.estacao}</td><td>{e.nome||e.tipo}</td><td>{i.categoria}</td><td>{i.estado}</td><td>{i.acao}</td><td>{i.custo||0} €</td></tr>})}</tbody></table></div></section>}
 {tab==='relatorios'&&<section className="card"><h2>Relatórios</h2><select value={sel} onChange={e=>setSel(e.target.value)}><option value="">Selecionar edifício...</option>{edificios.map(e=><option key={e.id} value={e.id}>{e.estacao} — {e.nome||e.tipo}</option>)}</select><button className="btn" onClick={()=>gerarPdf(sel)}>Gerar PDF</button><button className="btn secondary" onClick={exportarExcel}>Exportar Excel</button></section>}
 <p className="footer-note">EDF_Oeste · Autor RJP</p></main></div>
}

createRoot(document.getElementById('root')).render(<App/>)
