
import React,{useState}from'react'
import{createRoot}from'react-dom/client'
import jsPDF from'jspdf'
import'./style.css'

const ICON='/ip-logo.png'
const LS='edf_bridge_cfg'
function load(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function today(){return new Date().toISOString().slice(0,10)}
function badge(e){return ['Crítico','Mau','Alta','Urgente'].includes(e)?'danger':['Razoável','Média'].includes(e)?'warn':'ok'}
async function bridge(url,action,payload={}){
 if(!url)throw new Error('Falta o URL do Google Apps Script')
 const r=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})})
 const t=await r.text()
 try{return JSON.parse(t)}catch{return{ok:false,error:t}}
}
function file64(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(file)})}

function App(){
 const[tab,setTab]=useState('dashboard')
 const[cfg,setCfg]=useState(load(LS,{scriptUrl:''}))
 const[status,setStatus]=useState('Desligado')
 const[estacoes,setEstacoes]=useState([])
 const[edificios,setEdificios]=useState([])
 const[classificacao,setClassificacao]=useState([])
 const[inspecoes,setInspecoes]=useState([])
 const[fotos,setFotos]=useState([])
 const[pdfs,setPdfs]=useState([])
 const[excel,setExcel]=useState([])
 const[sel,setSel]=useState('')
 const[insp,setInsp]=useState({data:today(),categoria:'Cobertura',estado:'Razoável',gravidade:'Média',prazo:'',responsavel:'RJP',descricao:'',acao:'',custo:'',fotos:[]})
 const allEd=[...classificacao,...edificios].filter((v,i,a)=>a.findIndex(x=>String(x.ID)===String(v.ID))===i)
 const ed=allEd.find(e=>String(e.ID)===String(sel))
 const nav=[['dashboard','Dashboard'],['setup','Google Bridge'],['excel','Importar Excel'],['linha','Linha do Oeste'],['edificios','Edifícios'],['inspecoes','Inspeções'],['drive','Drive'],['calendar','Calendar'],['relatorios','PDF']]

 async function testar(){try{setStatus('A testar...');const r=await bridge(cfg.scriptUrl,'ping');if(!r.ok)throw new Error(r.error||'Erro');setStatus('Ligação OK');alert('Ligação OK')}catch(e){setStatus('Erro: '+e.message);alert(e.message)}}
 async function criarEstrutura(){try{setStatus('A criar estrutura...');const r=await bridge(cfg.scriptUrl,'ensureStructure');if(!r.ok)throw new Error(r.error||'Erro');setStatus('Estrutura criada');alert('Estrutura Google criada')}catch(e){setStatus('Erro: '+e.message);alert(e.message)}}
 async function lerBase(){try{setStatus('A ler base...');const r=await bridge(cfg.scriptUrl,'readDb');if(!r.ok)throw new Error(r.error||'Erro');setEstacoes(r.estacoes||[]);setEdificios(r.edificios||[]);setClassificacao(r.classificacao||[]);setInspecoes(r.inspecoes||[]);setFotos(r.fotos||[]);setPdfs(r.pdfs||[]);setStatus('Base carregada')}catch(e){setStatus('Erro: '+e.message);alert(e.message)}}
 async function procurarExcel(){try{setStatus('A procurar Excel...');const r=await bridge(cfg.scriptUrl,'findExcelFiles');if(!r.ok)throw new Error(r.error||'Erro');setExcel(r.files||[]);setStatus(`Encontrados ${(r.files||[]).length} Excel`)}catch(e){setStatus('Erro: '+e.message);alert(e.message)}}
 async function atualizarTudo(){try{setStatus('A importar Excel...');const r=await bridge(cfg.scriptUrl,'importExcel');if(!r.ok)throw new Error(r.error||'Erro');setEstacoes(r.estacoes||[]);setEdificios(r.edificios||[]);setClassificacao(r.classificacao||[]);setExcel(r.files||[]);setStatus(`Atualizado: ${r.estacoes?.length||0} estações, ${r.edificios?.length||0} edifícios, ${r.classificacao?.length||0} classificações`)}catch(e){setStatus('Erro: '+e.message);alert(e.message)}}
 async function addFotos(e){if(!ed)return alert('Seleciona edifício');const station=ed.Localização||ed['Estação/Local']||ed.Estação||'Sem_Estacao';const added=[];for(const file of [...e.target.files]){setStatus('A enviar foto...');const base64=await file64(file);const r=await bridge(cfg.scriptUrl,'uploadFile',{folderStation:station,subfolder:'Fotos',fileName:file.name,mimeType:file.type||'image/jpeg',base64,meta:{EdificioID:ed.ID,Estação:station,Data:today(),Autor:'RJP'}});if(!r.ok)throw new Error(r.error||'Erro foto');added.push(r.record)}setFotos([...added,...fotos]);setInsp({...insp,fotos:[...insp.fotos,...added]});setStatus('Fotos no Drive')}
 async function guardarInspecao(){if(!ed)return alert('Seleciona edifício');const station=ed.Localização||ed['Estação/Local']||ed.Estação||'Sem_Estacao';const rec={ID:crypto.randomUUID(),EdificioID:ed.ID,Estação:station,Data:insp.data,Categoria:insp.categoria,Estado:insp.estado,Gravidade:insp.gravidade,Prazo:insp.prazo,Responsável:insp.responsavel,Descrição:insp.descricao,Ação:insp.acao,Custo:insp.custo,Fotos:(insp.fotos||[]).map(f=>f.Link).join(' | '),Autor:'RJP'};try{setStatus('A guardar inspeção...');const r=await bridge(cfg.scriptUrl,'append',{sheet:'Inspecoes',record:rec});if(!r.ok)throw new Error(r.error||'Erro');setInspecoes([rec,...inspecoes]);setInsp({...insp,descricao:'',acao:'',custo:'',fotos:[]});setStatus('Inspeção guardada')}catch(e){setStatus('Erro: '+e.message);alert(e.message)}}
 async function gerarPdfDrive(){if(!ed)return alert('Seleciona edifício');const station=ed.Localização||ed['Estação/Local']||ed.Estação||'Sem_Estacao';const pdf=new jsPDF();let y=13;pdf.setFillColor(23,181,164);pdf.rect(0,0,210,28,'F');pdf.setTextColor(255,255,255);pdf.setFontSize(17);pdf.text('EDF_Oeste',12,y);pdf.setFontSize(10);pdf.text('Gestão de Edifícios e Manutenção · Autor: RJP',12,20);pdf.setTextColor(0,0,0);pdf.setFontSize(13);pdf.text(`${station} | ${ed.ID} | PK ${ed.Pk||ed.PK||'-'}`,12,40);y=60;inspecoes.filter(i=>String(i.EdificioID)===String(ed.ID)).forEach((i,n)=>{if(y>270){pdf.addPage();y=20}pdf.text(`${n+1}. ${i.Data} - ${i.Categoria} - ${i.Estado}`,12,y);y+=7;pdf.text(pdf.splitTextToSize(i.Descrição||'-',180),12,y);y+=14});const blob=pdf.output('blob');const base64=await file64(new File([blob],`EDF_Oeste_${ed.ID}_${today()}.pdf`,{type:'application/pdf'}));try{setStatus('A guardar PDF...');const r=await bridge(cfg.scriptUrl,'uploadFile',{folderStation:station,subfolder:'PDF',fileName:`EDF_Oeste_${ed.ID}_${today()}.pdf`,mimeType:'application/pdf',base64,meta:{EdificioID:ed.ID,Estação:station,Data:today(),Autor:'RJP'}});if(!r.ok)throw new Error(r.error||'Erro');setPdfs([r.record,...pdfs]);setStatus('PDF no Drive');alert('PDF guardado')}catch(e){setStatus('Erro: '+e.message);alert(e.message)}}
 async function criarEvento(){if(!ed||!insp.prazo)return alert('Seleciona edifício e prazo');const station=ed.Localização||ed['Estação/Local']||ed.Estação||'Sem_Estacao';try{const r=await bridge(cfg.scriptUrl,'createCalendarEvent',{event:{summary:`EDF_Oeste - ${station} - ${insp.categoria}`,description:insp.acao||insp.descricao,date:insp.prazo}});if(!r.ok)throw new Error(r.error||'Erro');setStatus('Evento criado')}catch(e){setStatus('Erro: '+e.message);alert(e.message)}}

 return <div><header className="top"><div className="brand"><img className="brand-logo" src={ICON}/><div><h1>EDF_Oeste</h1><p>Gestão de Edifícios e Manutenção</p><div className="author">Autor: RJP · Google Bridge</div></div></div></header><nav className="tabs">{nav.map(([id,n])=><button key={id} onClick={()=>setTab(id)} className={'tab '+(tab===id?'active':'')}>{n}</button>)}</nav><main className="container">
 {tab==='dashboard'&&<section className="grid"><div className="card"><h3>Estações</h3><div className="kpi">{estacoes.length}</div></div><div className="card"><h3>Edifícios</h3><div className="kpi">{allEd.length}</div></div><div className="card"><h3>Inspeções</h3><div className="kpi">{inspecoes.length}</div></div><div className="card"><h3>Fotos</h3><div className="kpi">{fotos.length}</div></div><div className="card"><h3>Estado</h3><p>{status}</p></div></section>}
 {tab==='setup'&&<section className="grid"><div className="card"><h2>Google Bridge</h2><label>URL do Google Apps Script</label><input value={cfg.scriptUrl} onChange={e=>setCfg({...cfg,scriptUrl:e.target.value})} placeholder="https://script.google.com/macros/s/.../exec"/><button className="btn" onClick={()=>{save(LS,cfg);alert('Guardado')}}>Guardar</button><button className="btn secondary" onClick={testar}>Testar ligação</button><button className="btn secondary" onClick={criarEstrutura}>Criar estrutura Google</button><button className="btn secondary" onClick={lerBase}>Ler base</button></div><div className="card"><h3>Sem login na APK</h3><p>A APK e a WebApp guardam tudo através do Google Apps Script, na tua conta Google.</p></div></section>}
 {tab==='excel'&&<section className="grid"><div className="card"><h2>Importar Excel do Drive</h2><p>Pasta esperada: <b>Edificios Oeste</b></p><button className="btn" onClick={procurarExcel}>Procurar Excel</button><button className="btn secondary" onClick={atualizarTudo}>Atualizar Tudo</button><p className="small">{status}</p></div><div className="card"><h3>Ficheiros encontrados</h3>{excel.map(f=><div className="item" key={f.id}><div className="thumb">📊</div><div><b>{f.name}</b><div className="small">{f.modifiedTime}</div><a href={f.webViewLink} target="_blank">Abrir no Drive</a></div></div>)}</div></section>}
 {tab==='linha'&&<section className="card"><h2>Linha do Oeste</h2>{estacoes.map(e=><div className="item" key={(e.Pk||'')+(e.Localização||'')}><div className="thumb">🚉</div><div><b>{e.Localização}</b><div className="small">PK {e.Pk||e.PK||'-'} · {e['Utilização Principal']||''}</div></div></div>)}</section>}
 {tab==='edificios'&&<section className="card"><h2>Edifícios</h2>{allEd.map(e=><div className="item" key={e.ID}><div className="thumb">🏢</div><div><b>{e.Localização||e['Estação/Local']||e.Estação}</b><div className="small">{e.ID} · PK {e.Pk||e.PK||'-'} · {e['Utilização Principal']||e['Tipo de edifício']||e.Tipo||''}</div><span className={'badge '+badge(e['Estado global'])}>{e['Estado global']||'A avaliar'}</span><br/><button className="btn secondary" onClick={()=>{setSel(e.ID);setTab('inspecoes')}}>Selecionar</button></div></div>)}</section>}
 {tab==='inspecoes'&&<section className="grid"><div className="card"><h2>Nova inspeção</h2><label>Edifício</label><select value={sel} onChange={e=>setSel(e.target.value)}><option value="">Selecionar</option>{allEd.map(e=><option key={e.ID} value={e.ID}>{e.Localização||e['Estação/Local']} - {e.ID}</option>)}</select><div className="row"><div><label>Data</label><input type="date" value={insp.data} onChange={e=>setInsp({...insp,data:e.target.value})}/></div><div><label>Categoria</label><input value={insp.categoria} onChange={e=>setInsp({...insp,categoria:e.target.value})}/></div></div><div className="row3"><div><label>Estado</label><select value={insp.estado} onChange={e=>setInsp({...insp,estado:e.target.value})}>{['Bom','Razoável','Mau','Crítico'].map(x=><option key={x}>{x}</option>)}</select></div><div><label>Gravidade</label><select value={insp.gravidade} onChange={e=>setInsp({...insp,gravidade:e.target.value})}>{['Baixa','Média','Alta','Urgente'].map(x=><option key={x}>{x}</option>)}</select></div><div><label>Prazo</label><input type="date" value={insp.prazo} onChange={e=>setInsp({...insp,prazo:e.target.value})}/></div></div><label>Descrição</label><textarea value={insp.descricao} onChange={e=>setInsp({...insp,descricao:e.target.value})}/><label>Ação</label><textarea value={insp.acao} onChange={e=>setInsp({...insp,acao:e.target.value})}/><label>Custo</label><input value={insp.custo} onChange={e=>setInsp({...insp,custo:e.target.value})}/><label>Fotos</label><input type="file" multiple accept="image/*" capture="environment" onChange={addFotos}/><button className="btn" onClick={guardarInspecao}>Guardar no Google</button><button className="btn secondary" onClick={criarEvento}>Criar evento Calendar</button></div><div className="card"><h2>Histórico</h2>{inspecoes.filter(i=>!sel||String(i.EdificioID)===String(sel)).map(i=><div className="item" key={i.ID}><div className="thumb">📋</div><div><b>{i.Data} - {i.Categoria}</b><br/><span className={'badge '+badge(i.Estado)}>{i.Estado}</span><p>{i.Descrição}</p></div></div>)}</div></section>}
 {tab==='drive'&&<section className="grid"><div className="card"><h2>Fotografias no Drive</h2>{fotos.map(f=><div className="item" key={f.ID}><div className="thumb">📷</div><div><b>{f.Estação}</b><div className="small">{f.Nome}</div><a href={f.Link} target="_blank">Abrir</a></div></div>)}</div><div className="card"><h2>PDF no Drive</h2>{pdfs.map(p=><div className="item" key={p.ID}><div className="thumb">📄</div><div><b>{p.Estação}</b><div className="small">{p.Nome}</div><a href={p.Link} target="_blank">Abrir</a></div></div>)}</div></section>}
 {tab==='calendar'&&<section className="card"><h2>Google Calendar</h2><button className="btn" onClick={criarEvento}>Criar evento</button></section>}
 {tab==='relatorios'&&<section className="card"><h2>Relatório PDF</h2><select value={sel} onChange={e=>setSel(e.target.value)}><option value="">Selecionar edifício</option>{allEd.map(e=><option key={e.ID} value={e.ID}>{e.Localização||e['Estação/Local']} - {e.ID}</option>)}</select><button className="btn" onClick={gerarPdfDrive}>Gerar PDF e guardar no Drive</button></section>}
 </main><p className="footer-note">EDF_Oeste · Autor RJP · APK e WebApp ligadas por Google Apps Script</p></div>
}
createRoot(document.getElementById('root')).render(<App/>)
